### ISSUE TITLE
C++ Version

### ISSUE THREAD

**Issue by vietanhdev** [VinAIResearch/PhoWhisper#1]
Hello,
Thank you for sharing this project with the public. It's great to see a project like this supporting Vietnamese language. I'm wondering if there are any plans to convert this model to C++, similar to the Whisper.CPP project (https://github.com/ggerganov/whisper.cpp). Having a C++ implementation would allow us to utilize this model on low-power PCs or mobile devices. I'm also curious if this model addresses the issues that were encountered with the Whisper model from OpenAI when working with Vietnamese. The related URLs for the issues are:
- https://github.com/ggerganov/whisper.cpp/issues/1051
- https://github.com/openai/whisper/discussions/961
Thank you for your attention to this matter!

**Comment by datquocnguyen** [comment]
Could you or someone else give it a try and observe the outcome? 
Your input would be greatly appreciated.

**Comment by duykhanhbk** [comment]
@vietanhdev I really tried convert phoWhisper model (base, large version) to CT2 (C++ like faster whisper) and it works well, I'll try with Whisper.cpp later (I really like llama.cpp) and I see the problem with phoWhisper when I try inference by chunked size, the transcription output really long (not correspond with chunk size) compare with Whisper-large v3 @datquocnguyen (I think this is because of the dataset use for training finetuning, is this correct?)

**Comment by vietanhdev** [comment]
Could your contribute your instruction / conversion code to this repo? It would be very helpful.
Thank you! 😁

**Comment by bvqbao** [comment]
Do you guys succeed in converting PhoWhisper to gguf? I tried it with the provided script in whisper.cpp (convert-h5-to-ggml.py) but the output of the gguf model is garbage. There's something wrong here.

**Comment by ILG2021** [comment]
I suggest to use ctranslate2, the speed is faster than whisper cpp, and it is easy to use in python.

**Comment by chiendo97** [comment]
> Do you guys succeed in converting PhoWhisper to gguf? I tried it with the provided script in whisper.cpp (convert-h5-to-ggml.py) but the output of the gguf model is garbage. There's something wrong here.

@bvqbao You can try to add `-nt` option when using whisper.cpp. The hallucination will disappear.
