### ISSUE TITLE
Train in my datasets?

### ISSUE THREAD

**Issue by PhamMinhTien05102001** [VinAIResearch/PhoWhisper#2]
Hello team VinAI, I have been waiting for a long time for the speech to text task, please help me train it on my dataset (vietnamese, how to train, struct folder)

**Comment by minhduc210196** [comment]
@PhamMinhTien05102001 
I also have the same problem with you

**Comment by datquocnguyen** [comment]
See: https://github.com/huggingface/transformers/blob/main/examples/pytorch/speech-recognition/README.md#whisper-model
