### ISSUE TITLE
Is it possible to train the model with multi lingual languages ? 

### ISSUE THREAD

**Issue by leviethung2103** [VinAIResearch/PhoWhisper#4]
Hi VinAI Team,

Given a audio that speaker mainly speaks 90% of time in Vietnamese, 10% of time in English.  I've tested your model with this type of audio and English words are interpreted as Vietnamese language.

I am thinking of re-train the model with a dataset that contains the English and Vietnamese in transcript. Do you think this approach is feasible or not ? 

Thank you

**Comment by Fannovel16** [comment]
It's possible as the base Whisper is already a multilingual ASR model
