### ISSUE TITLE
Which Vietnamese Accents are included in the dataset?

### ISSUE THREAD

**Issue by chungvle** [VinAIResearch/PhoWhisper#6]
Thank you for releasing PhoWhisper for Vietnamese! Your paper describes a large-scale ASR dataset that includes a diverse array of Vietnamese accents from different regions in Vietnam. Could you kindly elaborate on that, e.g.:
- which regions are included, e.g. Hue, Saigon, etc?
- is the dataset open source? or is it proprietary?
- is it possible to collaborate, for example adding a missing dialect, or enhancing the dataset? Thank you, kindly.

**Comment by datquocnguyen** [comment]
We do not plan to open-source the dataset atm. 
And due to our GenAI policy, we cannot share much information about this dataset.
